<<<<<<< HEAD
[tool.poetry]
name = "flask-app"
version = "0.1.0"
description = ""
authors = ["Zach-hammad <Zh395@drexel.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^2.3.2"
gunicorn = "^23.0.0"
boto3 = "^1.35.67"
python-dotenv = "^1.0.0"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
=======
[tool.poetry]
name = "flask-app"
version = "0.1.0"
description = ""
authors = ["Zach-hammad <Zh395@drexel.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.1.0"
gunicorn = "^23.0.0"
boto3 = "^1.35.67"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
>>>>>>> gitSync
